/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uabc.meta1_1ayd;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class AdminAgendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminAgendaGUI
     */
    public AdminAgendaGUI() {
        initComponents();
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = jTable1.getSelectedRow();
                if (fila != -1) { // hay fila seleccionada
                    String idPersona = jTable1.getValueAt(fila, 0).toString();
                    String nombre = jTable1.getValueAt(fila, 1).toString();
                    String direccion = jTable1.getValueAt(fila, 2).toString();

                    // 🔹 Cargar en los JTextField
                    NombrePersona.setText(nombre);
                    DireccionPersona.setText(direccion);

                    // 🔹 Cargar teléfonos
                    cargarTelefonos(idPersona);
                }
            }
        });   
        jTable2.getSelectionModel().addListSelectionListener(e -> {
            if(!e.getValueIsAdjusting()) {
                int fila = jTable2.getSelectedRow();
                if(fila != -1) {
                    String numero = jTable2.getValueAt(fila, 1).toString();
                    NombrePersona1.setText(numero);
                }
            }
        }); 
        ModificarTelefono.addActionListener(e -> {
            int filaPersona = jTable1.getSelectedRow();
            if(filaPersona == -1) {
                Estado.setText("Seleccione primero una persona.");
                return;
            }

            String idPersona = jTable1.getValueAt(filaPersona, 0).toString();
            String nuevoNombre = NombrePersona.getText();
            String nuevaDireccion = DireccionPersona.getText();

            // Modificar persona si cambió algo
            AdministradorAgenda.modificarPersona(idPersona, nuevoNombre, nuevaDireccion);

            int filaTelefono = jTable2.getSelectedRow();
            if(filaTelefono != -1) {
                String idTelefono = jTable2.getValueAt(filaTelefono, 0).toString(); // columna 0 = idTelefono
                String nuevoNumero = NombrePersona1.getText();
                AdministradorAgenda.modificarTelefono(idTelefono, nuevoNumero);
            }

            Estado.setText("Datos modificados correctamente.");
            cargarTablas();
            cargarTelefonos(idPersona);
        });
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        AltaPersona = new javax.swing.JButton();
        BajaPersona = new javax.swing.JButton();
        ModificarTelefono = new javax.swing.JButton();
        NombrePersona = new javax.swing.JTextField();
        DireccionPersona = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        NombrePersona1 = new javax.swing.JTextField();
        AgregarTelefono1 = new javax.swing.JButton();
        AgregarTelefono2 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD AGENDA DB");
        setResizable(false);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setText("AGENDA");

        Estado.setEditable(false);
        Estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Estado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        AltaPersona.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AltaPersona.setText("ALTA");
        AltaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPersonaActionPerformed(evt);
            }
        });

        BajaPersona.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BajaPersona.setText("BAJA");
        BajaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaPersonaActionPerformed(evt);
            }
        });

        ModificarTelefono.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ModificarTelefono.setText("MODIFICAR");
        ModificarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTelefonoActionPerformed(evt);
            }
        });

        NombrePersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NombrePersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        NombrePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersonaActionPerformed(evt);
            }
        });

        DireccionPersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DireccionPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));
        DireccionPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionPersonaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Telefono", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setShowGrid(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        NombrePersona1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NombrePersona1.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefonos"));
        NombrePersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersona1ActionPerformed(evt);
            }
        });

        AgregarTelefono1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AgregarTelefono1.setText("AGREGAR TEL");
        AgregarTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTelefono1ActionPerformed(evt);
            }
        });

        AgregarTelefono2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AgregarTelefono2.setText("QUITAR TEL");
        AgregarTelefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTelefono2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DireccionPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(NombrePersona, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombrePersona1)
                            .addComponent(Estado))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BajaPersona)
                            .addComponent(AltaPersona))
                        .addGap(18, 18, 18)
                        .addComponent(ModificarTelefono)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgregarTelefono1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarTelefono2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ModificarTelefono)))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarTelefono1)
                            .addComponent(AltaPersona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgregarTelefono2)
                            .addComponent(BajaPersona))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombrePersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DireccionPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionPersonaActionPerformed

    private void NombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePersonaActionPerformed

    private void AltaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPersonaActionPerformed
        String nombre = NombrePersona.getText();
        String direccion = DireccionPersona.getText();
        if(nombre.isEmpty() || direccion.isEmpty()){
            Estado.setText("Agregue nombre y direccion.");
            return;
        }
        
        int res = AdministradorAgenda.altaPersona(nombre, direccion);
        if(res==1){
            Estado.setText("Persona agregada correctamente: " + nombre);
            cargarTablas();
        }else{
            Estado.setText("No se pudo agregar la persona.");
        }
    }//GEN-LAST:event_AltaPersonaActionPerformed

    private void BajaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaPersonaActionPerformed
        int fila = jTable1.getSelectedRow(); // obtener fila seleccionada
        if (fila == -1) { // ninguna fila seleccionada
            Estado.setText("Seleccione una persona para eliminar.");
            return;
        }

        // Obtener ID de la persona
        int idPersona = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());

        // Llamar al método de baja
        int res = AdministradorAgenda.bajaPersona(idPersona);

        if (res == 1) {
            Estado.setText("Persona eliminada correctamente.");
            cargarTablas(); // refrescar tabla de personas
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"Id Tel", "Número"} // solo dos columnas
            ));
            NombrePersona.setText(""); // limpiar JTextField
            DireccionPersona.setText("");
        } else {
            Estado.setText("No se pudo eliminar la persona.");
        }
        
    }//GEN-LAST:event_BajaPersonaActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void NombrePersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePersona1ActionPerformed

    private void AgregarTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTelefono1ActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            Estado.setText("Seleccione primero una persona.");
            return;
        }

        String idPersona = jTable1.getValueAt(fila, 0).toString();
        String numero = NombrePersona1.getText();

        if (numero.isEmpty()) {
            Estado.setText("Ingrese un número de teléfono.");
            return;
        }

        int res = AdministradorAgenda.agregarTelefono(idPersona, numero);
        if (res == 1) {
            Estado.setText("Teléfono agregado correctamente.");
            cargarTelefonos(idPersona); // refrescar tabla de teléfonos
            NombrePersona1.setText(""); // limpiar campo
        } else {
            Estado.setText("No se pudo agregar el teléfono.");
        }
    }//GEN-LAST:event_AgregarTelefono1ActionPerformed

    private void AgregarTelefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTelefono2ActionPerformed
        int fila = jTable2.getSelectedRow();
        if (fila == -1) {
            Estado.setText("Seleccione un teléfono para eliminar.");
            return;
        }

        // Obtener ID del teléfono
        String idTelefono = jTable2.getValueAt(fila, 0).toString(); // o columna 1 si cambiaste la tabla
        String idPersona = jTable2.getValueAt(fila, 1).toString();  // si necesitas refrescar la tabla

        // Llamar al método de baja
        int res = AdministradorAgenda.bajaTelefono(idTelefono);
        if (res == 1) {
            Estado.setText("Teléfono eliminado correctamente.");
            NombrePersona1.setText(""); 
            cargarTelefonos(idPersona); // refrescar tabla de teléfonos
        } else {
            Estado.setText("No se pudo eliminar el teléfono.");
        }
    }//GEN-LAST:event_AgregarTelefono2ActionPerformed

    private void ModificarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAgendaGUI().setVisible(true);
            }
        });
    }
    
    private void cargarTablas() {
        ArrayList<Persona> personas = AdministradorAgenda.obtenerPersonas();

        // ---- Tabla Personas ----
        DefaultTableModel modelPersonas = (DefaultTableModel) jTable1.getModel();
        modelPersonas.setRowCount(0);
        for (Persona p : personas) {
            modelPersonas.addRow(new Object[]{ p.getId(), p.getNombre(), p.getDireccion() });
        }

        // Teléfonos se cargarán dinámicamente al seleccionar una persona
    }
    
    private void cargarTelefonos(String idPersona) {
        DefaultTableModel modelTelefonos = (DefaultTableModel) jTable2.getModel();
        modelTelefonos.setRowCount(0); // limpiar

        ArrayList<Persona> personas = AdministradorAgenda.obtenerPersonas();

        for (Persona p : personas) {
            if (p.getId().equals(idPersona)) {
                for (Telefono t : p.getTelefonos()) {
                    // Solo idTel y numero
                    modelTelefonos.addRow(new Object[]{ t.getIdTel(), t.getNumero() });
                }
                break;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarTelefono1;
    private javax.swing.JButton AgregarTelefono2;
    private javax.swing.JButton AltaPersona;
    private javax.swing.JButton BajaPersona;
    private javax.swing.JTextField DireccionPersona;
    private javax.swing.JTextField Estado;
    private javax.swing.JButton ModificarTelefono;
    private javax.swing.JTextField NombrePersona;
    private javax.swing.JTextField NombrePersona1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
