/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uabc.meta1_1ayd;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class AdminAgendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminAgendaGUI
     */
    public AdminAgendaGUI() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30); 
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(270);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(30); 
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(230);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(30); 
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(360);
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = jTable1.getSelectedRow();
                if (fila != -1) {
                    String idPersona = jTable1.getValueAt(fila, 0).toString();
                    String nombre = jTable1.getValueAt(fila, 1).toString();

                    Nombre.setText(nombre);
                    Direccion.setText(""); // Limpiar el campo de dirección

                    cargarTelefonos(idPersona);
                    cargarDirecciones(idPersona);
                }
            }
        }); 
        jTable3.getSelectionModel().addListSelectionListener(e -> {
            if(!e.getValueIsAdjusting()) {
                int fila = jTable3.getSelectedRow();
                if(fila != -1) {
                    String numero = jTable3.getValueAt(fila, 1).toString();
                    Telefono.setText(numero);
                }
            }
        }); 
        Modificar.addActionListener(e -> {
            int filaPersona = jTable1.getSelectedRow();
            if(filaPersona == -1) {
                Estado.setText("Seleccione primero una persona.");
                return;
            }

            String idPersona = jTable1.getValueAt(filaPersona, 0).toString();
            String nuevoNombre = Nombre.getText();
            String nuevaDireccion = Direccion.getText();

            AdministradorAgenda.modificarPersona(idPersona, nuevoNombre, nuevaDireccion);

            int filaTelefono = jTable3.getSelectedRow();
            if(filaTelefono != -1) {
                String idTelefono = jTable3.getValueAt(filaTelefono, 0).toString(); // columna 0 = idTelefono
                String nuevoNumero = Telefono.getText();
                AdministradorAgenda.modificarTelefono(idTelefono, nuevoNumero);
            }

            Estado.setText("Datos modificados correctamente.");
            cargarTablas();
            cargarTelefonos(idPersona);
        });
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        AltaPersona = new javax.swing.JButton();
        BajaPersona = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Telefono = new javax.swing.JTextField();
        AgregarTelefono = new javax.swing.JButton();
        QuitarTelefono = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        AgregarCalle = new javax.swing.JButton();
        QuitarCalle = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD AGENDA DB");
        setResizable(false);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setText("AGENDA");

        Estado.setEditable(false);
        Estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Estado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        AltaPersona.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AltaPersona.setText("ALTA");
        AltaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPersonaActionPerformed(evt);
            }
        });

        BajaPersona.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BajaPersona.setText("BAJA");
        BajaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaPersonaActionPerformed(evt);
            }
        });

        Modificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        Direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Telefono", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setShowGrid(true);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefonos"));
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });

        AgregarTelefono.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AgregarTelefono.setText("AGREGAR TEL");
        AgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTelefonoActionPerformed(evt);
            }
        });

        QuitarTelefono.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuitarTelefono.setText("QUITAR TEL");
        QuitarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarTelefonoActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdCalle", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setShowGrid(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        AgregarCalle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AgregarCalle.setText("AGREGAR CALLE");
        AgregarCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCalleActionPerformed(evt);
            }
        });

        QuitarCalle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuitarCalle.setText("QUITAR CALLE");
        QuitarCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarCalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Direccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefono)
                            .addComponent(Estado))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BajaPersona)
                            .addComponent(AltaPersona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarCalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuitarCalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgregarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuitarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Titulo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AgregarTelefono)
                                .addComponent(AgregarCalle))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(QuitarTelefono)
                                .addComponent(QuitarCalle))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AltaPersona)
                            .addGap(7, 7, 7)
                            .addComponent(BajaPersona))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(Modificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void AltaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPersonaActionPerformed
        String nombre = Nombre.getText();

        if(nombre.isEmpty()){
            Estado.setText("Agregue un nombre.");
            return;
        }

        int res = AdministradorAgenda.altaPersona(nombre, ""); // Segundo parámetro vacío
        if(res==1){
            Estado.setText("Persona agregada correctamente: " + nombre);
            cargarTablas();
            Nombre.setText(""); // Limpiar campo
        }else{
            Estado.setText("No se pudo agregar la persona.");
        }
    }//GEN-LAST:event_AltaPersonaActionPerformed

    private void BajaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaPersonaActionPerformed
        int fila = jTable1.getSelectedRow(); // obtener fila seleccionada
        if (fila == -1) { // ninguna fila seleccionada
            Estado.setText("Seleccione una persona para eliminar.");
            return;
        }

        int idPersona = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());

        int res = AdministradorAgenda.bajaPersona(idPersona);

        if (res == 1) {
            Estado.setText("Persona eliminada correctamente.");
            cargarTablas(); 
            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"Id Tel", "Número"} 
            ));
            Nombre.setText("");
            Direccion.setText("");
        } else {
            Estado.setText("No se pudo eliminar la persona.");
        }
        
    }//GEN-LAST:event_BajaPersonaActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void AgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTelefonoActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            Estado.setText("Seleccione primero una persona.");
            return;
        }

        String idPersona = jTable1.getValueAt(fila, 0).toString();
        String numero = Telefono.getText();

        if (numero.isEmpty()) {
            Estado.setText("Ingrese un número de teléfono.");
            return;
        }

        int res = AdministradorAgenda.agregarTelefono(idPersona, numero);
        if (res == 1) {
            Estado.setText("Teléfono agregado correctamente.");
            cargarTelefonos(idPersona); 
            Telefono.setText(""); 
        } else {
            Estado.setText("No se pudo agregar el teléfono.");
        }
    }//GEN-LAST:event_AgregarTelefonoActionPerformed

    private void QuitarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarTelefonoActionPerformed
        int filaTel = jTable3.getSelectedRow();
        int filaPersona = jTable1.getSelectedRow();

        if (filaTel == -1) {
            Estado.setText("Seleccione un teléfono para eliminar.");
            return;
        }
        if (filaPersona == -1) {
            Estado.setText("Seleccione primero una persona.");
            return;
        }

        String idTelefono = jTable3.getValueAt(filaTel, 0).toString();
        String idPersona = jTable1.getValueAt(filaPersona, 0).toString(); // idPersona viene de la tabla de personas

        int res = AdministradorAgenda.bajaTelefono(idTelefono);
        if (res == 1) {
            Estado.setText("Teléfono eliminado correctamente.");
            Telefono.setText(""); 
            cargarTelefonos(idPersona); 
        } else {
            Estado.setText("No se pudo eliminar el teléfono.");
        }
    }//GEN-LAST:event_QuitarTelefonoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void AgregarCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCalleActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            Estado.setText("Seleccione primero una persona.");
            return;
        }

        String idPersona = jTable1.getValueAt(fila, 0).toString();

        // Puedes usar el campo Direccion o crear uno nuevo específico para calles
        String calle = Direccion.getText(); 

        if (calle.isEmpty()) {
            Estado.setText("Ingrese una calle/dirección.");
            return;
        }

        int res = AdministradorAgenda.agregarDireccion(idPersona, calle);
        if (res == 1) {
            Estado.setText("Dirección agregada correctamente.");
            cargarDirecciones(idPersona);
            Direccion.setText(""); 
        } else {
            Estado.setText("No se pudo agregar la dirección.");
        }
    }//GEN-LAST:event_AgregarCalleActionPerformed

    private void QuitarCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarCalleActionPerformed
        int filaDir = jTable2.getSelectedRow();
        int filaPersona = jTable1.getSelectedRow();

        if (filaDir == -1) {
            Estado.setText("Seleccione una dirección para eliminar.");
            return;
        }
        if (filaPersona == -1) {
            Estado.setText("Seleccione primero una persona.");
            return;
        }

        String idDireccion = jTable2.getValueAt(filaDir, 0).toString();
        String idPersona = jTable1.getValueAt(filaPersona, 0).toString();

        int res = AdministradorAgenda.bajaDireccion(idDireccion);
        if (res == 1) {
            Estado.setText("Dirección eliminada correctamente.");
            cargarDirecciones(idPersona);
        } else {
            Estado.setText("No se pudo eliminar la dirección.");
        }
    }//GEN-LAST:event_QuitarCalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAgendaGUI().setVisible(true);
            }
        });
    }
    
    private void cargarTablas() {
        ArrayList<Persona> personas = AdministradorAgenda.obtenerPersonas();

        DefaultTableModel modelPersonas = (DefaultTableModel) jTable1.getModel();
        modelPersonas.setRowCount(0);
        for (Persona p : personas) {
            modelPersonas.addRow(new Object[]{ p.getId(), p.getNombre() });
        }
    }
    
    private void cargarTelefonos(String idPersona) {
        DefaultTableModel modelTelefonos = (DefaultTableModel) jTable3.getModel();
        modelTelefonos.setRowCount(0); 

        ArrayList<Persona> personas = AdministradorAgenda.obtenerPersonas();

        for (Persona p : personas) {
            if (p.getId().equals(idPersona)) {
                for (Telefono t : p.getTelefonos()) {
                    modelTelefonos.addRow(new Object[]{ t.getIdTel(), t.getNumero() });
                }
                break;
            }
        }
    }

    private void cargarDirecciones(String idPersona) {
        DefaultTableModel modelDirecciones = (DefaultTableModel) jTable2.getModel();
        modelDirecciones.setRowCount(0); 

        ArrayList<Persona> personas = AdministradorAgenda.obtenerPersonas();

        for (Persona p : personas) {
            if (p.getId().equals(idPersona)) {
                for (Direccion d : p.getDirecciones()) {
                    modelDirecciones.addRow(new Object[]{ d.getIdCalle(), d.getCalle() });
                }
                break;
            }
        }
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCalle;
    private javax.swing.JButton AgregarTelefono;
    private javax.swing.JButton AltaPersona;
    private javax.swing.JButton BajaPersona;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Estado;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton QuitarCalle;
    private javax.swing.JButton QuitarTelefono;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
